name: Generate and Send User Info

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install setuptools
      run: |
        pip install setuptools

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python generate_user_info.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_ENABLED: true  # Set this to true or false
        LOGGING_ENABLED: true  # Set this to true or false
        EMAIL_ENABLED: true  # Set this to true or false
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        INCLUDE_IMAGE_INFO: true  # Set this to true or false
        EMAIL_SERVICE: gmail  # Set this to 'gmail' or 'outlook'
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
