name: Generate and Send User Info

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests faker apprise python-dotenv

    - name: Run script
      run: python generate_user_info.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_ENABLED: true  # Set this to true or false
        LOGGING_ENABLED: true  # Set this to true or false
        EMAIL_ENABLED: false  # Set this to true or false
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        INCLUDE_IMAGE_INFO: true  # Set this to true or false
