name: Generate Unique Indian Profile Info and Send to Discord

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Faker
        run: pip install faker

      - name: Generate Random Info
        id: generate_info
        run: |
          python -c "
          from faker import Faker
          import json
          fake = Faker('en_IN')
          data = {
              'name': fake.name(),
              'username': fake.user_name(),
              'bio': fake.sentence(nb_words=10),
              'location': fake.city(),
              'company': fake.company(),
              'website': fake.url()
          }
          print(f'::set-output name=data::{json.dumps(data)}')
          "

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          data=${{ steps.generate_info.outputs.data }}
          curl -H 'Content-Type: application/json' -d "$data" $DISCORD_WEBHOOK_URL
